name: Build

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false

      - name: Install Rust
        uses: dtolnay/rust-toolchain@d1031067263f94b142dd6c0ce24c5eb9d02d52a0 # stable
        with:
          toolchain: stable-x86_64-pc-windows-msvc

      - name: Check
        run: cargo check --locked

      - name: Test
        run: cargo test --locked

      - name: Release build
        run: cargo build --release --locked
